theme: jekyll-theme-slate #jekyll-theme-slate
title: MCE Hub
description: Somos un grupo de estudiantes y graduados de la maestría en cómputo estadístico del CIMAT Monterrey, interesados en la Ciencia de Datos.

