theme: jekyll-theme-cayman #jekyll-theme-slate
title: MCE Hub
description: Somos un grupo de estudiantes y graduados de la maestría en cómputo estadístico del CIMAT Monterrey, interesados en la Ciencia de Datos.

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"

avatar: https://github.com/mcehub/mcehub.github.io/blob/master/mcehub_logo.png
logo: https://github.com/mcehub/mcehub.github.io/blob/master/mcehub_logo.png
